### PR TITLE
Add a Makefile target to mount or extract the fat16 fs embedded in ISOs

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by hamishcoleman** [comment]
Is there really a need to actually mount the filesystem?  I dont want to add sudo commands to this (this would be the first bit that needed them)

**Comment by ypid** [comment]
> Is there really a need to actually mount the filesystem?

It could be useful when you want to make changes to the fat16 fs interactively. For me, it was not obvious at first how to get to the files in the fat16 fs so maybe the mount could stay to document possible options.

**Comment by hamishcoleman** [comment]
It sounds more like that there should be some extra documentation to document the mount process.

Oh, and using the '-m' option to mcopy gives me crazy datestamps from the future:
`make: Warning: File `g2uj25us.iso.orig.extract' has modification time 2.5e+09 s in the future`

**Comment by ypid** [comment]
> Oh, and using the '-m' option to mcopy gives me crazy datestamps from the future:

Removed. Can you have another look at this PR?

**Pull request merged**
